version: "3.9"
services:
  db:
    image: postgres:16
    container_name: garita_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: garita_db
    ports:
      - "5432:5432"
    volumes:
      - datos_postgres:/var/lib/postgresql/data
  backend:
    build: ./backend
    container_name: garita_backend
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
  frontend:
    build: ./frontend
    container_name: garita_frontend
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
volumes:
  datos_postgres:
